apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-root-vol
  namespace: example
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4096Gi

