apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      hostname: example-deployment
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/nrp-testing
        operator: Exists
      - effect: NoSchedule
        key: nautilus.io/prism-center
        operator: Exists
      securityContext:
        fsGroup: 100 
      containers:
      - name: example-deployment 
        image: gitlab-registry.nrp-nautilus.io/tet/ont-k8s:6caa43f9
        # image: gitlab-registry.nrp-nautilus.io/tet/ont-k8s:fc233605
        # image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/minimal:v1.3
        securityContext:
          capabilities:
            add: ["IPC_LOCK", "SYS_ADMIN", "SYS_PTRACE"]
        env:
        - name: TZ
          value: "America/Los_Angeles"
#         - name: SIZEW
#           value: "1920"
#         - name: SIZEH
#           value: "1200"
#         - name: REFRESH
#           value: "60"
#         - name: DPI
#           value: "96"
#         - name: CDEPTH
#           value: "24"
#         # Choose either `value:` or `secretKeyRef:` but not both at the same time
#         - name: PASSWD
# #          value: "mypasswd"
          # valueFrom:
          #   secretKeyRef:
          #     name: my-pass
          #     key: my-pass
        # Uncomment this to enable noVNC, disabing selkies-gstreamer and ignoring all its parameters except `BASIC_AUTH_PASSWORD`, which will be used for authentication with noVNC, `BASIC_AUTH_PASSWORD` defaults to `PASSWD` if not provided
        # - name: NOVNC_ENABLE
        #   value: "true"
        # Additional view-only password only applicable to the noVNC interface, choose either `value:` or `secretKeyRef:` but not both at the same time
#        - name: NOVNC_VIEWPASS
#          value: "mypasswd"
#          valueFrom:
#            secretKeyRef:
#              name: my-pass
#              key: my-pass


        # # Uncomment below to use a TURN server for improved network compatibility
        # ###
        # - name: TURN_HOST
        #   value: "turn.nrp-nautilus.io"
        # - name: TURN_PORT
        #   value: "3478"
        # Provide only `TURN_SHARED_SECRET` for time-limited shared secret authentication or both `TURN_USERNAME` and `TURN_PASSWORD` for legacy long-term authentication, but do not provide both authentication methods at the same time
        # - name: TURN_SHARED_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-pass
        #       key: turn-secret

        # # Change to `tcp` if the UDP protocol is throttled or blocked in your client network, or when the TURN server does not support UDP
        # - name: TURN_PROTOCOL
        #   value: "udp"
        # # You need a valid hostname and a certificate from authorities such as ZeroSSL (Let's Encrypt may have issues) to enable this
        # - name: TURN_TLS
        #   value: "false"
        stdin: true
        tty: true
        ports:
        - containerPort: 5901
          protocol: TCP
        - containerPort: 7001
          protocol: TCP
        resources:
          limits:
            memory: 128Gi
            cpu: "64"
            ephemeral-storage: 96Gi
            # amd.com/xilinx_u55c_gen3x16_xdma_base_3-0: 1
#            nvidia.com/gpu: 1
          requests:
            memory: 64Gi
            cpu: "32"
            ephemeral-storage: 96Gi
            # amd.com/xilinx_u55c_gen3x16_xdma_base_3-0: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /cache
          name: example-deployment-cache-vol
        - mountPath: /data
          name: example-deployment-data-vol
        - mountPath: /home/profiling-user
          name: example-deployment-root-vol
        - mountPath: /ramdisk
          name: ram-disk
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: ram-disk
        emptyDir:
          medium: Memory
      - name: example-deployment-cache-vol
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: example-deployment-cache-vol
      - name: example-deployment-data-vol
        persistentVolumeClaim:
          claimName: example-deployment-data-vol #snn-storage-shared #example-deployment-data-vol      
      - name: example-deployment-root-vol
        persistentVolumeClaim:
          claimName: example-deployment-root-vol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                # - hostname, e.g. node-1-4.sdsc.optiputer.net
