apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-data-vol
  namespace: example
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi

